$schema = "./node_modules/wrangler/config-schema.json"
name = "viscerium-codex"
pages_build_output_dir = "./dist"
compatibility_date = "2026-07-09"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "24"
SITE_URL = "https://codex.viscerium.co.uk"
CONTACT_FROM_EMAIL = "contact@mail.viscerium.co.uk"
CONTACT_TO_EMAIL = "contact@viscerium.co.uk"
CONTACT_VERIFICATION_PROVIDER = "turnstile"
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAADyoq-9zwp5ep4hG"
